name: dixa_messenger_flutter
description: "A new Flutter plugin project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.dixa_messenger_flutter
        pluginClass: DixaMessengerFlutterPlugin
      ios:
        pluginClass: DixaMessengerFlutterPlugin
